project_id = "lofzfrmwtlsugmlzbrfn"

[functions.mongodb]
verify_jwt = false

[functions.auth-mongodb]
verify_jwt = false

[functions.properties-mongodb]
verify_jwt = false

[functions.send-valuation-alert]
verify_jwt = false

[functions.check-valuation-changes]
verify_jwt = false
